spring:
  jackson:
    default-property-inclusion: non_null
server:
  port: 8083
springfox:
  title: ZenDesk Sync
  version: 1.0.0
fint:
  zendesk:
    users:
      enabled: true
    tickets:
      enabled: true
