spring:
  jackson:
    default-property-inclusion: non_null
server:
  port: 8083
springfox:
  title: ZenDesk Sync
  version: 1.0.0
fint:
  zendesk:
    ticket-priorities:
      - name: Lav
        value: low
        help: >
          Velg prioritet ut fra følgende kriterier:
          <ul>  <li>Mindre feil eller hendelser.</li>
          <li>Feil påvirker arbeidet, men sluttbruker kan fortsette sitt arbeid med noe redusert ytelse.</li>
          <li> Innspill til videreutvikling.</li>
          </ul>
      - name: Normal
        value: normal
        help: >
          Velg prioritet ut fra følgende kriterier:
          <ul>
          <li>En sluttbruker får ikke utført arbeidsoppgavene sine.</li>
          <li>En sluttbruker opplever at systemet henger og ytelsen er betraktelig redusert</li>
          </ul>
      - name: Høy
        value: high
        help: >
          Velg prioritet ut fra følgende kriterier:
          <ul>
          <li>Flere brukere får ikke utført arbeidsoppgavene sine.</li>
          </ul>
          NB! Det forventes at dere er tilgjengelige frem til saken er løst og har mulighet til å bistå oss med hjelp og informasjon.
      - name: Haster
        value: urgent
        help: >
          Velg prioritet ut fra følgende kriterier:
          <ul>
          <li>Tjenesten ligger nede.</li>
          <li>Ingen brukere får utført arbeidsoppgavene sine.</li>
          <li>Alvorlig konsekvens for omdømme.</li>
          </ul>
          NB! Det forventes at dere er tilgjengelige frem til saken er løst og har mulighet
           til å bistå oss med hjelp og informasjon.
    ticket-types:
      - name: Spørsmål
        value: question
        help: Velg denne om du lurer på noe eller trenger råd.
      - name: Hendelse
        value: incident
        help: Velg denne om det er en ikke planlagt hendelse/forstyrrelse/feil på en tjeneste.
      - name: Videreutvikling
        value: task
        help: Velg denne om du har forslag til videreutvikling.
    ticket-category:
      - name: QlikSense
      - name: QlikView
      - name: Hub
      - name: NPrinting
      - name: Analyse
        help: Her krysser du av dersom du har spørsmål knyttet til analyser av elev- og søkerdata som f.eks. overganger og utvalgsdefinisjoner.
