apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-zendesk-integration
  namespace: fintlabs-no
  labels:
    app.kubernetes.io/name: fint-zendesk-integration
    app.kubernetes.io/instance: fint-zendesk-integration_fintlabs_no
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: fint-core
    fintlabs.no/team: core
    fintlabs.no/org-id: fintlabs.no
spec:
  port: 8080
  imagePullPolicy: Always
  orgId: fintlabs.no
  image: ghcr.io/fintlabs/fint-zendesk-integration:latest
  url:
    hostname: kunde-beta.felleskomponent.no
    basePath: /zendesk
  envFrom:
    - secretRef:
        name: fint-portal-user
    - secretRef:
        name: zendesk-integration
  env:
    - name: JAVA_TOOL_OPTIONS
      value: '-XX:+ExitOnOutOfMemoryError -Xmx800M'
    - name: logging.level.no.fint.provisioning
      value: debug
    - name: fint.webclient.connection-provider.type
      value: NEW
    - name: fint.zendesk.timeout
      value: PT10S
    - name: fint.zendesk.prov.user.queuing.delay
      value: "600000"
  resources:
    limits:
      memory: "1Gi"
      cpu: "1"
    requests:
      memory: "512Mi"
      cpu: "250m"
  restartPolicy: Always
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate: { maxSurge: 1, maxUnavailable: 0 }